# Generated by Django 6.0.1 on 2026-01-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Выполнена'), ('overdue', 'Просрочена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
